message("*beep boop* loading libraries...")
suppressMessages(library(tidyverse))
suppressMessages(library(janitor))
suppressMessages(library(glue))
suppressMessages(library(ggtext))
suppressMessages(library(here))
suppressMessages(library(gridExtra))
suppressMessages(library(grid))
suppressMessages(library(broom))
suppressMessages(library(data.table))
# suppressMessages(library(vroom))
# suppressMessages(library(poLCA))
# suppressMessages(library(readxl))
# suppressMessages(library(ggridges))
# suppressMessages(library(ggcorrplot))
message("*beep boop* libraries loaded!")