message("*beep boop* loading libraries...")
suppressMessages(library(data.table))
suppressMessages(library(tidyverse))
suppressMessages(library(janitor))
suppressMessages(library(glue))
suppressMessages(library(ggtext))
suppressMessages(library(here))
suppressMessages(library(gridExtra))
suppressMessages(library(grid))
suppressMessages(library(broom))
suppressMessages(library(data.table))
message("*beep boop* libraries loaded!")